version: "3.8"
services:

  backend:
    build:
      context: ./Server/
    container_name: chatting-server
    ports:
      - "8000:8000"

  frontend:
    build:
      context: ./Client/
    container_name: chatting-client
    ports:
      - "3000:3000"

networks:
  my-network:
